### ISSUE TITLE
  uhd: U

### ISSUE THREAD

**Issue by bilalkhan1986** [SheldonZhong/CommunicationSystemDesign#7]
I am running simulink model with USRP. But i got uhd: U message on message on command window.
This is sampling time matching error. Can anybody help me to resolve this problem

**Comment by SheldonZhong** [comment]
Hey buddy, let's keep the issue panel clean, could you leave your email or other personal contacts. I will contact you personally.

**Comment by bilalkhan1986** [comment]
yes off course  tanoli.jamshed@gmail.com
wechat +8615619010605
